### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by adnan22222** [augustinbegue/icue-ambilight#32]
**only 1 of the 4 corsair vengeance RGB ram sticks is lighting up**
ambilight has been working perfectly for me, but it has been only lighting up 1 of my 4 ram sticks 

**Additional Information (please complete):**
 - Version : (release you used, if not the latest, please try to reproduce the bug with it)
 - Screenshot/paste of the logs :  (press Ctrl+Shift+I to access them)
 - Screenshot of the connected devices in **icue-ambilight**: (Settings Tab)
 - Screenshot of the connected devices in **iCue**:

![20210502_193437](https://user-images.githubusercontent.com/83560959/116833224-a1dfea00-ab7d-11eb-825d-30d84940641a.jpg)
![Screenshot (23)](https://user-images.githubusercontent.com/83560959/116833226-a6a49e00-ab7d-11eb-92ad-9cda6f748f12.png)
![Screenshot (24)](https://user-images.githubusercontent.com/83560959/116833227-a6a49e00-ab7d-11eb-8fff-92ec3f294c18.png)
![Screenshot (25)](https://user-images.githubusercontent.com/83560959/116833228-a73d3480-ab7d-11eb-9df6-dae56c7bdeaa.png)
![Screenshot (26)](https://user-images.githubusercontent.com/83560959/116833230-a73d3480-ab7d-11eb-9d6d-3f0e74b7c298.png)

**Comment by Tagueo** [comment]
Hi, have you tried tweaking the coordinates of the ram sticks in the layout tab so they are in the middle of the screen?
This is the only solution to your problem I can see right now.
I know this system isn't really intuitive, but I plan to work on a more visual one.
Also they are some weird compatibility issue that I can't solve at the moment since I obviously don't own every corsair device and can't test them in every layout possible
