### ISSUE TITLE
[REQUEST] Start with Windows and start minimized feature

### ISSUE THREAD

**Issue by severd8** [augustinbegue/icue-ambilight#37]
**Is your feature request related to a problem? No

These features would be great to have! This app is awesome; keep up the good work!

- Start with Windows
- Start minimized
- Disable devices

**Comment by augustinbegue** [comment]
Hi!
To begin, sorry for the extreme inactivity, school is giving me a hard time to find some free time 🙃...

You can currently disable devices by going into the layout page and unchecking the boxes:
![image](https://user-images.githubusercontent.com/33714922/147253543-9d696790-82a9-4be1-b9b9-bb50083ecc71.png)
Sadly, I think Corsair's sdk does not allow to completely disable a device and hand back its control to iCue.

For your other suggestions, I'll look into implementing them since it shouldn't be to hard.

Thanks for making theses requests!
